import th from 'constants/transfermarkt/TableHeaders';
import pt from 'constants/transfermarkt/ParsingTypes';

export default {
    [pt.ALL_LATEST_TRANSFERS]: th.ALL_LATEST_TRANSFERS_HEADER,
    [pt.SEARCH_CLUBS]: th.SEARCH_RESULTS_HEADER_CLUBS,
    [pt.SEARCH_PLAYERS]: th.SEARCH_RESULTS_HEADER_PLAYERS,
    [pt.TEAM_TRANSFERS_ARRIVALS]: th.TEAM_TRANSFERS_HEADER_ARRIVALS,
    [pt.TEAM_TRANSFERS_DEPARTURES]: th.TEAM_TRANSFERS_HEADER_DEPARTURES,
    [pt.PLAYER_TRANSFERS_HISTORY]: th.PLAYER_TRANSFERS_HISTORY_HEADER
};
