export const TABLE_CLASS_NAME = '.items';
export const TABLE_HEADER_CLASS_NAME = '.table-header';
export const MINIMUM_VALUE = 5.0;
export const MILLIONS = 'Mill.';
export const THOUSANDS = 'Th.';
export const LOAN_FEE = 'Loan fee:';
export const SUMMER_TRANSFERS = 's';
export const WINTER_TRANSFERS = 'w';
export const SEARCH_RESULTS_CLUBS = 'Search results: Clubs';
